export const SECTIONS = {
  FRONTEND: 'FRONTEND',
  BACKEND: 'BACKEND',
  DEVOPS: 'DEVOPS',
  VERSION_CONTROL: 'VERSION_CONTROL',
  OPERATING_SYSTEMS: 'OPERATING_SYSTEMS',
  AGILE: 'AGILE',
  TESTING: 'TESTING',
};

export const checkboxList = [
  {
    label: 'Front-End',
    name: SECTIONS.FRONTEND,
  },
  {
    label: 'Back-End & Databases',
    name: SECTIONS.BACKEND,
  },
  {
    label: 'DevOps and Tools',
    name: SECTIONS.DEVOPS,
  },
  {
    label: 'Testing and Quality Assurance',
    name: SECTIONS.TESTING,
  },
  {
    label: 'Version Control',
    name: SECTIONS.VERSION_CONTROL,
  },
  {
    label: 'Operating Systems',
    name: SECTIONS.OPERATING_SYSTEMS,
  },
  {
    label: 'Agile and Project Management',
    name: SECTIONS.AGILE,
  },
];

export const skillsets = [
  {
    name: 'React',
    icon: 'React',
    section: [SECTIONS.FRONTEND],
    rating: 5,
  },
  {
    name: 'Angular',
    icon: 'Angular',
    section: [SECTIONS.FRONTEND],
    rating: 1,
  },
  {
    name: 'AWS',
    icon: 'AWS',
    section: [SECTIONS.DEVOPS],
    rating: 3,
  },
  {
    name: 'Bitbucket',
    icon: 'Bitbucket',
    section: [SECTIONS.VERSION_CONTROL],
    rating: 3,
  },
  {
    name: 'Bootstrap',
    icon: 'Bootstrap',
    section: [SECTIONS.FRONTEND],
    rating: 3,
  },
  {
    name: 'Vue',
    icon: 'Vue',
    section: [SECTIONS.FRONTEND],
    rating: 1,
  },
  {
    name: 'CSS3',
    icon: 'CSS',
    section: [SECTIONS.FRONTEND],
    rating: 5,
  },
  {
    name: 'Confluence',
    icon: 'Confluence',
    section: [SECTIONS.AGILE],
    rating: 4,
  },
  {
    name: 'Docker',
    icon: 'Docker',
    section: [SECTIONS.DEVOPS],
    rating: 1,
  },
  {
    name: 'Figma',
    icon: 'Figma',
    section: [SECTIONS.FRONTEND],
    rating: 4,
  },
  {
    name: 'Git',
    icon: 'Git',
    section: [SECTIONS.VERSION_CONTROL],
    rating: 5,
  },
  {
    name: 'Github',
    icon: 'GithubIcon',
    section: [SECTIONS.VERSION_CONTROL],
    rating: 5,
  },
  {
    name: 'Gitlab',
    icon: 'Gitlab',
    section: [SECTIONS.VERSION_CONTROL],
    rating: 5,
  },
  {
    name: 'GraphQL',
    icon: 'Graphql',
    section: [SECTIONS.FRONTEND, SECTIONS.BACKEND],
    rating: 3,
  },
  {
    name: 'HTML5',
    icon: 'HTML',
    section: [SECTIONS.FRONTEND],
    rating: 5,
  },
  {
    name: 'Java',
    icon: 'Java',
    section: [SECTIONS.BACKEND],
    rating: 3,
  },
  {
    name: 'JavaScript',
    icon: 'Javascript',
    section: [SECTIONS.FRONTEND],
    rating: 5,
  },
  {
    name: 'Jest',
    icon: 'Jest',
    section: [SECTIONS.TESTING],
    rating: 4,
  },
  {
    name: 'JUnit',
    icon: 'Junit',
    section: [SECTIONS.TESTING],
    rating: 3,
  },
  {
    name: 'Jira',
    icon: 'Jira',
    section: [SECTIONS.AGILE],
    rating: 4,
  },
  {
    name: 'MongoDB',
    icon: 'Mongodb',
    section: [SECTIONS.BACKEND],
    rating: 3,
  },
  {
    name: 'NextJs',
    icon: 'Nextjs',
    section: [SECTIONS.FRONTEND],
    rating: 3,
  },
  {
    name: 'Spring',
    icon: 'Spring',
    section: [SECTIONS.BACKEND],
    rating: 3,
  },
  {
    name: 'Storybook',
    icon: 'Storybook',
    section: [SECTIONS.FRONTEND],
    rating: 4,
  },
  {
    name: 'Tailwind CSS',
    icon: 'Tailwindcss',
    section: [SECTIONS.FRONTEND],
    rating: 4,
  },
  {
    name: 'Terraform',
    icon: 'Terraform',
    section: [SECTIONS.DEVOPS],
    rating: 2,
  },
  {
    name: 'Typescript',
    icon: 'Typescript',
    section: [SECTIONS.FRONTEND],
    rating: 4,
  },
  {
    name: 'NodeJs',
    icon: 'Nodejs',
    section: [SECTIONS.BACKEND],
    rating: 4,
  },
  {
    name: 'ExpressJs',
    icon: 'Express',
    section: [SECTIONS.BACKEND],
    rating: 4,
  },
  {
    name: 'Python',
    icon: 'Python',
    section: [SECTIONS.BACKEND],
    rating: 2,
  },
  {
    name: 'Redux',
    icon: 'Redux',
    section: [SECTIONS.FRONTEND],
    rating: 5,
  },
  {
    name: 'Webpack',
    icon: 'Webpack',
    section: [SECTIONS.FRONTEND],
    rating: 2,
  },
  {
    name: 'Apple',
    icon: 'Apple',
    section: [SECTIONS.OPERATING_SYSTEMS],
    rating: 5,
  },
  {
    name: 'Windows',
    icon: 'Windows',
    section: [SECTIONS.OPERATING_SYSTEMS],
    rating: 5,
  },
  {
    name: 'Linux',
    icon: 'Linux',
    section: [SECTIONS.OPERATING_SYSTEMS],
    rating: 5,
  },
  {
    name: 'Postgressql',
    icon: 'Postgressql',
    section: [SECTIONS.BACKEND],
    rating: 2,
  },
  {
    name: 'Cypress',
    icon: 'Cypress',
    section: [SECTIONS.TESTING],
    rating: 2,
  },
];
