export const experiencesList = [
  {
    company: 'Affinity',
    role: 'Software Engineer II',
    startDate: '05/13/2024',
    endDate: null,
    isCurrent: true,
    isCoop: false,
    location: 'Toronto (Remote), Canada',
  },
  {
    company: 'fabric Inc.',
    role: 'Software Development Engineer II',
    startDate: '01/01/2023',
    endDate: '02/15/2024',
    isCurrent: false,
    isCoop: false,
    location: 'Toronto (Remote), Canada',
  },
  {
    company: 'fabric Inc.',
    role: 'Software Development Engineer I',
    startDate: '04/06/2021',
    endDate: '01/01/2023',
    isCurrent: false,
    isCoop: false,
    location: 'Toronto (Remote), Canada',
  },
  {
    company: 'Spot It Inc.',
    role: 'Frontend Developer / Freelance',
    startDate: '06/01/2020',
    endDate: '04/06/2021',
    isCurrent: false,
    isCoop: false,
    location: 'Toronto (Remote), Canada',
  },
  {
    company: 'Melotel Inc.',
    role: 'Customer Service & Technical Support Representative',
    startDate: '12/10/2018',
    endDate: '04/06/2021',
    isCurrent: false,
    isCoop: false,
    location: 'North York, Canada',
  },
  {
    company: 'Barrick Gold',
    role: 'Systems and Development Analyst',
    startDate: '09/01/2019',
    endDate: '12/31/2019',
    isCurrent: false,
    isCoop: true,
    location: 'Toronto, Canada',
  },
  {
    company: 'Blackberry Ltd',
    role: 'Application Support Specialist',
    startDate: '05/01/2016',
    endDate: '08/30/2016',
    isCurrent: false,
    isCoop: true,
    location: 'Waterloo, Canada',
  },
];

export const experienceParagraphs = [
  'Discovering my passion for software development was a transformative journey that unfolded organically throughout my career. Starting as a Technical Support Specialist, I gained an understanding of the intricacies of technology and the joy of solving technical challenges. As a Frontend Developer, I found myself increasingly drawn to the art of crafting user-friendly interfaces. With each role, I was learning, growing, and gradually realizing that software development was more than just a job; it was my passion.',
  'The transition from a Software Development Engineer I to a Software Development Engineer II marked a pivotal moment. It was during this time that I fully embraced the intricacies of software development, the thrill of coding, and the satisfaction of building robust solutions. The journey from support specialist to software engineer was a natural evolution, and my passion for software development became the guiding force that directed my career path.',
  'This diverse journey from customer service and technical support to software development has equipped me with a well-rounded skill set, a strong work ethic, a strong desire to learn, and a passion for innovation that I bring to every project I undertake.',
  // `In retrospect, my professional experiences provided the stepping stones that led me to my true calling. Software development isn't just what I do; it's an integral part of who I am, and I'm excited to continue my journey, fueling my passion for technology and innovation  with each new project I undertake.`,
];
